name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: test venv1
      run: /usr/bin/pip list
    - name: test venv2
      run: dpkg -l | grep env
    - name: test venv3
      run: /usr/bin/python3 -m venv -h
