name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        build:
        - name: debug
        - name: production
    steps:
    - uses: actions/checkout@v1
    - name: ls
      run: ls -alh; pwd
    - name: verify codegen
      run: ./test.sh
